/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_sites_clibonlineprogram_sentry_serial_PortData */

#ifndef _Included_com_google_sites_clibonlineprogram_sentry_serial_PortData
#define _Included_com_google_sites_clibonlineprogram_sentry_serial_PortData
#ifdef __cplusplus
extern "C" {
#endif
#undef com_google_sites_clibonlineprogram_sentry_serial_PortData_STORAGE
#define com_google_sites_clibonlineprogram_sentry_serial_PortData_STORAGE 1L
#undef com_google_sites_clibonlineprogram_sentry_serial_PortData_INPUT
#define com_google_sites_clibonlineprogram_sentry_serial_PortData_INPUT 2L
#undef com_google_sites_clibonlineprogram_sentry_serial_PortData_OUTPUT
#define com_google_sites_clibonlineprogram_sentry_serial_PortData_OUTPUT 4L
#undef com_google_sites_clibonlineprogram_sentry_serial_PortData_IO
#define com_google_sites_clibonlineprogram_sentry_serial_PortData_IO 6L
/*
 * Class:     com_google_sites_clibonlineprogram_sentry_serial_PortData
 * Method:    getType0
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_google_sites_clibonlineprogram_sentry_serial_PortData_getType0
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_google_sites_clibonlineprogram_sentry_serial_PortData
 * Method:    getLabel0
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_google_sites_clibonlineprogram_sentry_serial_PortData_getLabel0
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_google_sites_clibonlineprogram_sentry_serial_PortData
 * Method:    isOperationAllowed0
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_google_sites_clibonlineprogram_sentry_serial_PortData_isOperationAllowed0
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_google_sites_clibonlineprogram_sentry_serial_PortData
 * Method:    connect0
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_google_sites_clibonlineprogram_sentry_serial_PortData_connect0
  (JNIEnv *, jclass, jint);


#ifdef __cplusplus
}
#endif
#endif
